project_name: disco_model
run_name: disco_s3d_paper
use_wandb: true
gpu_ids: [0]
epochs: 30
batch_size: 32
num_workers: 4
image_log_freq: 1000
encoder_type: dptv2
decoder_type: rrp

dptv2_ckpt_path: checkpoints/depth_anything_v2_vits.pth
image_encoder: vits
freeze_image_backbone: true
feature_dim: 128
num_heads: 4
image_token_grid: [6, 40]
image_self_attn_layers: 1
pairwise_chunk_size: 16
lr: 1.0e-4
lr_scheduler: cosine
min_lr: 1.0e-5

datasets:
  dataset_type: s3d
  map_res: 0.02
  data_folder: datasets_s3d/Structured3D
  data_splits: datasets_s3d/Structured3D/split.yaml
  val_split: val
  floorplan_img_size: [256, 256]
  local_map_crop_size_meters: 5.0
  hard_negative:
    mode: mixed
  pose_aug:
    enable: true
    trans_range: 25
    rot_range: 0.26
