project_name: rrp_model
run_name: rrp_gibson_paper

encoder_type: dptv2
decoder_type: rrp

use_wandb: true
train: true
batch_size: 4
epochs: 400
gpu_ids: [0]
num_workers: 2
lr: 1e-3
optimizer: adamw
max_norm: 1.0
scheduler: cosine
warmup: false
warmup_epochs: 10
seed: 0

vision_encoder: flona_vint
encoding_size: 128
obs_encoder: efficientnet-b0
cond_predict_scale: false
mha_num_attention_heads: 4
mha_num_attention_layers: 4
mha_ff_dim_factor: 4
down_dims: [64, 128, 256]
num_diffusion_iters: 10
normalize: true
context_size: 0
alpha: 0.001
len_traj_pred: 32
d_min: 0.1
d_max: 20.0
d_hyp: -0.2
D: 128

image_size: [256, 256]
datasets:
  dataset_type: gibson
  map_res: 0.01
  data_folder: datasets_gibson/gibson_f
  data_splits: datasets_gibson/gibson_f/split.yaml
  val_split: test
  rgb_img_size: [640, 480]
  floorplan_img_size: [256, 256]
  rmd_ray_num: 8
  rmd_m1: 9
  rmd_m2: 9

print_log_freq: 500
image_log_freq: 500
num_images_log: 4
pairwise_test_freq: 0
eval_fraction: 1
wandb_log_freq: 1
eval_freq: 1

dptv2_ckpt_path: checkpoints/depth_anything_v2_vits.pth
